#!/usr/bin/env bash
set -euo pipefail
#
# release.sh — pbrain's reproducible release pipeline (PB-128).
#
# pbrain carries TWO version files that must never drift:
#   - VERSION                      → x.y.z.0   (four-part; the .0 is a build slot)
#   - .claude-plugin/plugin.json   → x.y.z     (SemVer; read by lib/update-check.sh)
# This script is the SOLE WRITER of both, so a bump touches them in lockstep.
#
# It also owns the CHANGELOG cut (## [Unreleased] → ## [x.y.z] — <date>, with a
# fresh empty [Unreleased] on top), the per-version "what's new" HTML doc that
# auto-opens on plugin update (PB-129, generated by lib/whats-new.sh), and the
# git tag + GitHub release (gh).
#
# Everything is DRY-RUN by default — nothing is written, committed, tagged, or
# published until you pass --apply. Re-running on an already-cut version is a
# no-op (idempotent), so a half-finished release is safe to resume.
#
# Subcommands:
#   release.sh current                  print the current version (x.y.z)
#   release.sh next <major|minor|patch> print what the next version WOULD be
#   release.sh bump <level> [--apply]   write VERSION + plugin.json to the next version
#   release.sh changelog [--version V] [--apply]
#                                       roll [Unreleased] → [V] — <today>
#   release.sh whats-new [--version V] [--apply]
#                                       generate docs/whats-new/<V>.html from the CHANGELOG
#   release.sh cut <level> [--apply]    bump + changelog + whats-new in one shot
#   release.sh tag [--version V] [--apply]
#                                       create + push the vV git tag
#   release.sh publish [--version V] [--apply]
#                                       gh release create vV with notes from the CHANGELOG
#
# Env:
#   PBRAIN_RELEASE_DATE=YYYY-MM-DD   override the changelog date (default: today)
#   PBRAIN_RELEASE_REMOTE=origin     git remote to push tag to (default: origin)

_SCRIPT_DIR="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -P -- "$_SCRIPT_DIR/.." && pwd -P)"

VERSION_FILE="$REPO_ROOT/VERSION"
PLUGIN_JSON="$REPO_ROOT/.claude-plugin/plugin.json"
CHANGELOG="$REPO_ROOT/CHANGELOG.md"
WHATS_NEW_LIB="$REPO_ROOT/lib/whats-new.sh"

# ---- helpers ---------------------------------------------------------------

die()  { printf 'release: %s\n' "$*" >&2; exit 1; }
note() { printf '%s\n' "$*" >&2; }

# Current SemVer x.y.z, read from plugin.json (the canonical SemVer source).
current_version() {
  python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$PLUGIN_JSON" 2>/dev/null \
    || die "could not read version from $PLUGIN_JSON"
}

# Validate x.y.z. Echoes back on success.
require_semver() {
  printf '%s' "$1" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$' || die "not a SemVer x.y.z: '$1'"
  printf '%s' "$1"
}

# next_version <cur x.y.z> <major|minor|patch>
next_version() {
  local cur="$1" level="$2" major minor patch
  IFS=. read -r major minor patch <<<"$cur"
  case "$level" in
    major) major=$((major+1)); minor=0; patch=0 ;;
    minor) minor=$((minor+1)); patch=0 ;;
    patch) patch=$((patch+1)) ;;
    *) die "level must be major|minor|patch, got '$level'" ;;
  esac
  printf '%s.%s.%s' "$major" "$minor" "$patch"
}

today() { printf '%s' "${PBRAIN_RELEASE_DATE:-$(date +%F)}"; }

# Write both version files to <x.y.z>. Idempotent.
write_version_files() {
  local v="$1"
  printf '%s.0\n' "$v" > "$VERSION_FILE"
  python3 - "$PLUGIN_JSON" "$v" <<'PY'
import json, sys
path, ver = sys.argv[1], sys.argv[2]
with open(path) as f:
    data = json.load(f)
data["version"] = ver
with open(path, "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write("\n")
PY
}

# Does the CHANGELOG already have a ## [<v>] section?
changelog_has_version() {
  local v="$1"
  grep -qE "^## \[${v//./\\.}\]" "$CHANGELOG"
}

# Roll ## [Unreleased] → ## [<v>] — <date>, leaving a fresh empty [Unreleased].
# Idempotent: if [<v>] already exists, does nothing.
cut_changelog() {
  local v="$1" date="$2"
  python3 - "$CHANGELOG" "$v" "$date" <<'PY'
import sys, re
path, ver, date = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(path).read()
if re.search(r'^## \[' + re.escape(ver) + r'\]', text, flags=re.M):
    sys.exit(0)  # already cut — idempotent no-op
# Insert the versioned header right after the [Unreleased] header line,
# leaving [Unreleased] in place (empty) on top.
m = re.search(r'^## \[Unreleased\][^\n]*\n', text, flags=re.M)
if not m:
    sys.stderr.write("release: no '## [Unreleased]' section in CHANGELOG\n")
    sys.exit(3)
insert = "\n## [%s] — %s\n" % (ver, date)
out = text[:m.end()] + insert + text[m.end():]
open(path, "w").write(out)
PY
}

# The markdown that feeds the what's-new renderer for <v>: an authored
# highlights file (docs/whats-new/<v>.md) if it exists — a marketing-style guide
# with hero + per-feature sections + "try it" blocks — else the changelog
# section as a fallback so a release always produces a page.
whats_new_source() {
  local v="$1"
  local hl="$REPO_ROOT/docs/whats-new/$v.md"
  if [[ -f "$hl" ]]; then cat "$hl"; else changelog_section "$v"; fi
}

# Extract the body of the ## [<v>] section (between its header and the next ##).
changelog_section() {
  local v="$1"
  python3 - "$CHANGELOG" "$v" <<'PY'
import sys, re
path, ver = sys.argv[1], sys.argv[2]
text = open(path).read()
m = re.search(r'^## \[' + re.escape(ver) + r'\][^\n]*\n(.*?)(?=^## |\Z)',
              text, flags=re.M | re.S)
if not m:
    sys.exit(4)
sys.stdout.write(m.group(1).strip() + "\n")
PY
}

require_clean_or_dry() {
  $APPLY || return 0
  # Only the release-owned files may already be dirty (e.g. re-running cut).
  local dirty
  dirty="$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null \
    | grep -vE ' (VERSION|\.claude-plugin/plugin\.json|CHANGELOG\.md|docs/whats-new/)' || true)"
  [[ -z "$dirty" ]] || note "release: note — unrelated changes present in the worktree:
$dirty"
}

# ---- arg parsing -----------------------------------------------------------

APPLY=false
VERSION_ARG=""
SUB="${1:-}"; shift || true
ARGS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply)   APPLY=true ;;
    --version) VERSION_ARG="${2:-}"; shift ;;
    --version=*) VERSION_ARG="${1#*=}" ;;
    *) ARGS+=("$1") ;;
  esac
  shift
done

prefix() { $APPLY && printf '' || printf '[dry-run] '; }

# ---- subcommands -----------------------------------------------------------

case "$SUB" in
  current)
    current_version
    ;;

  next)
    [[ ${#ARGS[@]} -ge 1 ]] || die "usage: release.sh next <major|minor|patch>"
    next_version "$(current_version)" "${ARGS[0]}"
    ;;

  bump)
    [[ ${#ARGS[@]} -ge 1 ]] || die "usage: release.sh bump <major|minor|patch> [--apply]"
    cur="$(current_version)"
    new="$(next_version "$cur" "${ARGS[0]}")"
    note "$(prefix)bump $cur → $new (VERSION + plugin.json)"
    if $APPLY; then write_version_files "$new"; fi
    printf '%s\n' "$new"
    ;;

  changelog)
    v="$(require_semver "${VERSION_ARG:-$(current_version)}")"
    date="$(today)"
    if changelog_has_version "$v"; then
      note "changelog: [$v] already present — nothing to do"
    else
      note "$(prefix)changelog: cut [Unreleased] → [$v] — $date"
      if $APPLY; then cut_changelog "$v" "$date"; fi
    fi
    ;;

  whats-new)
    v="$(require_semver "${VERSION_ARG:-$(current_version)}")"
    [[ -f "$WHATS_NEW_LIB" ]] || die "missing $WHATS_NEW_LIB"
    out="$REPO_ROOT/docs/whats-new/$v.html"
    note "$(prefix)whats-new: generate docs/whats-new/$v.html"
    if $APPLY; then
      mkdir -p "$(dirname "$out")"
      whats_new_source "$v" | bash "$WHATS_NEW_LIB" render "$v" > "$out.tmp"
      mv "$out.tmp" "$out"
      note "wrote $out"
    fi
    ;;

  cut)
    [[ ${#ARGS[@]} -ge 1 ]] || die "usage: release.sh cut <major|minor|patch> [--apply]"
    require_clean_or_dry
    cur="$(current_version)"
    new="$(next_version "$cur" "${ARGS[0]}")"
    date="$(today)"
    note "$(prefix)cut $cur → $new (bump + changelog + whats-new), date $date"
    if $APPLY; then
      write_version_files "$new"
      cut_changelog "$new" "$date" || true
      if [[ -f "$WHATS_NEW_LIB" ]]; then
        mkdir -p "$REPO_ROOT/docs/whats-new"
        whats_new_source "$new" | bash "$WHATS_NEW_LIB" render "$new" \
          > "$REPO_ROOT/docs/whats-new/$new.html"
      fi
      note "cut $new — review the diff, then: scripts/release.sh tag --apply && scripts/release.sh publish --apply"
    fi
    printf '%s\n' "$new"
    ;;

  tag)
    v="$(require_semver "${VERSION_ARG:-$(current_version)}")"
    remote="${PBRAIN_RELEASE_REMOTE:-origin}"
    note "$(prefix)tag v$v + push to $remote"
    if $APPLY; then
      if git -C "$REPO_ROOT" rev-parse "v$v" >/dev/null 2>&1; then
        note "tag v$v already exists — skipping create"
      else
        git -C "$REPO_ROOT" tag -a "v$v" -m "pbrain v$v"
      fi
      git -C "$REPO_ROOT" push "$remote" "v$v"
    fi
    ;;

  publish)
    v="$(require_semver "${VERSION_ARG:-$(current_version)}")"
    command -v gh >/dev/null 2>&1 || die "gh not installed — create the release manually at https://github.com/baymac/pbrain/releases/new"
    note "$(prefix)gh release create v$v (notes from CHANGELOG [$v])"
    if $APPLY; then
      if gh release view "v$v" >/dev/null 2>&1; then
        note "release v$v already exists — skipping"
      else
        changelog_section "$v" | gh release create "v$v" \
          --title "pbrain v$v" --notes-file -
      fi
    fi
    ;;

  ""|-h|--help|help)
    sed -n '2,40p' "$_SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")" | sed 's/^# \{0,1\}//'
    ;;

  *)
    die "unknown subcommand '$SUB' (try: current|next|bump|changelog|whats-new|cut|tag|publish)"
    ;;
esac
